version: '3.8'

services:
    mongodb:
        image: mongo:4.4.13
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db

        command: mongod --auth